framework:
    messenger:
        default_bus: command.bus
        
        buses:
            command.bus: ~
            query.bus: ~

        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            async: '%env(MESSENGER_TRANSPORT_DSN)%'
            # failed: 'doctrine://default?queue_name=failed'
            # sync: 'sync://'

        routing:
            # Route your messages to the transports
            'Tocda\Message\Command\*': async

when@test:
    framework:
        messenger:
            transports:
                # replace with your transport name here (e.g., my_transport: 'in-memory://')
                # For more Messenger testing tools, see https://github.com/zenstruck/messenger-test
                async: test://
                sync: sync://
                othersync: test://
            routing:
                '*': async
                'Tocda\Message\Query\*': sync
