# Development environment override
services:
  todo-cda-php:
    build:
      context: .
      target: frankenphp_dev
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-nseven"
      - "traefik.http.routers.todo-cda-php.rule=Host(`todo-cda.api.local`)"
      - "traefik.http.routers.todo-cda-php.entrypoints=websecure"
      - "traefik.http.routers.todo-cda-php.tls=true"
      - "traefik.http.routers.todo-cda-php.tls.certresolver=default"
      - "traefik.http.services.todo-cda-php.loadbalancer.server.port=80"
      - "traefik.http.services.todo-cda-php.loadbalancer.server.scheme=http"
    volumes:
      - ./:/app:delegated
      - ./frankenphp/Caddyfile:/etc/caddy/Caddyfile:ro
      - ./frankenphp/conf.d/20-app.dev.ini:/usr/local/etc/php/app.conf.d/20-app.dev.ini:ro
    environment:
      MERCURE_EXTRA_DIRECTIVES: demo
      XDEBUG_MODE: "${XDEBUG_MODE:-off}"
    extra_hosts:
      - host.docker.internal:host-gateway
    tty: true
    networks:
      - traefik-nseven
      - todo-cda-network

  ###> symfony/mercure-bundle ###
  ###< symfony/mercure-bundle ###

  todo-cda-rabbitmq:
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-nseven"
      - "traefik.http.routers.todo-cda-rabbitmq.rule=Host(`todo-cda.r.local`)"
      - "traefik.http.routers.todo-cda-rabbitmq.entrypoints=websecure"
      - "traefik.http.routers.todo-cda-rabbitmq.tls=true"
      - "traefik.http.routers.todo-cda-rabbitmq.tls.certresolver=default"
      - "traefik.http.services.todo-cda-rabbitmq.loadbalancer.server.port=15672"

  todo-cda-worker:
    volumes:
      - ./:/app

###> doctrine/doctrine-bundle ###
###< doctrine/doctrine-bundle ###

networks:
  traefik-nseven:
    external: true
  todo-cda-network:
    driver: bridge